#!/usr/bin/env escript
%%! -name pe@130.229.169.176 -setcookie omglol -connect_all false

main(_) ->
    make:all(),
	%% {'pe@130.229.181.78'}},
     fixture:manual(),
%%	fixture:add({leader,'t4202@130.229.146.238'}),
%%	fixture:add({leader,'toni@130.229.173.8'}),
		io:fread("wait for other shell", "~s")
.

